spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/liquibase_db
        username: root
        password: root

    liquibase:
        change-log: classpath:db/changelog/db.changelog.yaml
        default-schema: liquibase_db

preliquibase:
    sqlScriptReferences: classpath:db/changelog/schema/SCHEMA.sql
    enabled: false